- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - backup.openeverest.io
  resources:
    - backupclasses
    - backupstorages
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - backup.openeverest.io
  resources:
    - backups
    - restores
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - backup.openeverest.io
  resources:
    - backups/status
    - restores/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - barmancloud.cnpg.io
  resources:
    - objectstores
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - barmancloud.cnpg.io
  resources:
    - objectstores/status
  verbs:
    - get
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/finalizers
  verbs:
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - providers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - postgresql.cnpg.io
  resources:
    - backups
    - clusters
    - scheduledbackups
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - postgresql.cnpg.io
  resources:
    - backups/status
    - clusters/status
  verbs:
    - get
