apiVersion: v2
name: provider-cloudnative-pg
description: A Helm chart for deploying the OpenEverest provider-cloudnative-pg provider
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - openeverest
  - provider
  - database
home: https://github.com/adityapimpalkar/provider-cloudnative-pg
sources:
  - https://github.com/adityapimpalkar/provider-cloudnative-pg
maintainers:
  - name: Aditya Pimpalkar
dependencies:
  - name: cloudnative-pg
    version: "0.28.3"
    repository: https://cloudnative-pg.github.io/charts
    condition: cloudnative-pg.enabled
