# Minimal Instance CR — smallest viable configuration.
apiVersion: core.openeverest.io/v1alpha1
kind: Instance
metadata:
  name: my-database-simple
spec:
  provider: provider-cloudnative-pg
  components:
    engine:
      type: postgresql
      replicas: 3
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      storage:
        size: 5Gi
